name: Linting

on: pull_request
jobs:
  lint_python:
    name: "Lint and code analysis"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.8"
            channel-priority: "flexible"
            envfile: ".github/environment-lint.yml"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache conda
      uses: actions/cache@v3
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ matrix.python-version }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles( matrix.envfile ) }}
    - name: Install conda environmnent
      uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        add-pip-as-python-dependency: true
        auto-activate-base: false
        activate-environment: lint
        # mamba-version: "*"
        channel-priority: ${{ matrix.channel-priority }}
        environment-file: ${{ matrix.envfile }}
        use-only-tar-bz2: false

    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info -a
        conda list

    - name: (flake8) Style check
      shell: bash -l {0}
      run: flake8 mirdata --count --select=E9,F63,F7,F82 --show-source --statistics
      # Info about error codes: https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
      # and https://flake8.pycqa.org/en/latest/user/error-codes.html
    
    - name: (mypy) Type check package
      shell: bash -l {0}
      run: python -m mypy mirdata --ignore-missing-imports --allow-subclassing-any